sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /camera/depth_registered/points
   max_range: 3.0
   padding_scale: 4.0
   padding_offset: 0.18
   point_subsample: 1
